id: quiz_basic_types_vs_js
learningObjectives:
  - Differentiate between basic types in JavaScript and TypeScript.
hints:
  - Recall that TypeScript uses static typing.
  - Think about how we add types in TypeScript compared to JavaScript.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Ready for a little quiz action to break up our learning?
          - text: Let's see if you can spot the difference between basic types in JavaScript
              and TypeScript!
          - text: What's a key difference between basic types in JavaScript and TypeScript?
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - TypeScript has static typing with type declarations; JavaScript does
            not.
          - JavaScript can't work with strings and numbers.
          - TypeScript uses dynamic typing just like JavaScript.
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Fantastic! You've nailed it. TypeScript's static typing is a crucial
                      feature that distinguishes it from JavaScript.
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Close, but not quite. JavaScript can work with strings and numbers, but it
                      doesn't use static typing like TypeScript does. Try again.
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Oops! That's not right. TypeScript employs static typing, unlike
                      JavaScript's dynamic nature. Give it another shot.
            - actionId: replay_action
              params:
                actionName: quiz
